### ISSUE TITLE
Better error handling of faulty input to Safir.Dob.Typesystem.Serialization.ToObject()

### ISSUE THREAD

**Issue by fumpa** [SafirSDK/safir-sdk-core#350] opened 2017-04-24 07:07 UTC
When using Safir.Dob.Typesystem.Serialization.ToObject() in C# (not tested for C++) we sometimes gets a System.AccessViolationException.
"An unhandled exception of type 'System.AccessViolationException' occurred in Safir.Dob.Typesystem.dll
Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

The input in our case is a string with only one space character (' ').
Some simple checks ought to be done in ToObject method to avoid this and throw a Safir exception instead that has a better description of the reason why the exception occurred.

**Comment by DonOregano** [comment] 2023-06-16 11:59
This is probably a duplicate of #409, which is fixed.

**Closed by DonOregano** 2023-06-16 11:59 UTC
